spring:
  mail:
    default-encoding: UTF-8
    host: mail.kiccghana.com
    port: 26
    username: singlessummit@kiccghana.com
    password: SS2022.Champion
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 15000
          timeout: 15000
          debug: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/ssRegistration?useSSL=false
    username: root
    password:
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


app:
  configuration:
    sendGridApiKey: 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
    accessKey: AKIA5BMUX5KS25P2HQ2Z
    secret: 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


server:
  port: 8089


